name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'
  release:
    types: [created]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checar código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Instalar dependências
        run: |
          cd Front
          npm install

      - name: Compilar e gerar pacotes
        run: |
          cd Front
          npm run build
          npm run dist

      - name: Fazer upload dos artefatos (para Debug)
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ runner.os }}
          path: Front/dist/

      - name: Upload dos pacotes `.deb` e `.exe` para o Release do GitHub
        uses: softprops/action-gh-release@v1
        with:
          files: |
            Front/dist/*.deb
            Front/dist/*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
